services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    env_file:
      - .env.docker

    environment:
      DATABASE_URL: "dbname=production_rag user=postgres password=postgres host=db port=5432"

    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg17

    environment:
      POSTGRES_DB: production_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d production_rag"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: